DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(100) NOT NULL,
    `Description` TEXT NOT NULL,
    `Price` DECIMAL(6,2) NOT NULL,
    `Color` VARCHAR(30) NOT NULL,
    `Pattern` VARCHAR(30) NOT NULL,
    `Brand` VARCHAR(50) NOT NULL DEFAULT '3-Shirts',
    `Size` VARCHAR(10) NOT NULL,
    `Image` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`ID`)
);
