DROP TABLE IF EXISTS `products`;

CREATE TABLE `products` (
    `ID` INT NOT NULL AUTO_INCREMENT,
    `Name` VARCHAR(100) NOT NULL,
    `Description` TEXT NOT NULL,
    `Price` DECIMAL(6,2) NOT NULL,
    `Color` VARCHAR(30) NOT NULL,
    `Pattern` VARCHAR(30) NOT NULL,
    `Brand` VARCHAR(50) NOT NULL DEFAULT '3-Shirts',
    `Size` VARCHAR(10) NOT NULL,
    `Stock` BOOLEAN NOT NULL DEFAULT FALSE,
    `Image` VARCHAR(255) DEFAULT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE users (
    userId INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role ENUM('user', 'admin') NOT NULL DEFAULT 'user',
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
