/* ID not needed, the SQL schema handles this for us automatically */
INSERT INTO `products`
(`Name`, `Description`, `Price`, `Color`, `Pattern`, `Brand`, `Size`, `Image`)
VALUES

('Classic Crew Tee',
 'A soft, everyday cotton crew neck designed for comfort and durability. Perfect for layering or wearing on its own.',
 20.00,
 'White',
 'Solid',
 '3-Shirts',
 'M',
 'classic-crew-white.jpg'),

('Classic Crew Tee',
 'A soft, everyday cotton crew neck designed for comfort and durability. Perfect for layering or wearing on its own.',
 20.00,
 'Black',
 'Solid',
 '3-Shirts',
 'L',
 'classic-crew-black.jpg'),

('Heather Grey Essential Tee',
 'Lightweight heathered cotton blend with a modern athletic fit. Breathable fabric ideal for daily wear.',
 22.00,
 'Heather Grey',
 'Solid',
 '3-Shirts',
 'M',
 'heather-grey-essential.jpg'),

('Navy Core T-Shirt',
 'Premium ring-spun cotton with reinforced stitching for long-lasting wear and shape retention.',
 24.00,
 'Navy',
 'Solid',
 '3-Shirts',
 'L',
 'navy-core-tee.jpg'),

('Vintage Logo Graphic Tee',
 'Soft-washed fabric featuring a retro-inspired 3-Shirts logo print with a relaxed everyday fit.',
 28.00,
 'Charcoal',
 'Graphic',
 '3-Shirts',
 'M',
 'vintage-logo-charcoal.jpg'),

('Mountain Line Art Tee',
 'Minimalist mountain line artwork printed with high-quality ink on breathable cotton.',
 26.00,
 'Forest Green',
 'Graphic',
 '3-Shirts',
 'L',
 'mountain-line-green.jpg'),

('Striped Casual Tee',
 'Classic horizontal stripe pattern with a tailored fit. Made from midweight combed cotton.',
 25.00,
 'White/Navy',
 'Striped',
 '3-Shirts',
 'M',
 'striped-white-navy.jpg'),

('Premium Heavyweight Tee',
 'Thick, structured cotton tee with a slightly oversized cut for a modern streetwear feel.',
 32.00,
 'Black',
 'Solid',
 '3-Shirts',
 'L',
 'heavyweight-black.jpg'),

('Summer Sand Tee',
 'Lightweight breathable cotton designed for warm weather comfort and relaxed styling.',
 21.00,
 'Sand',
 'Solid',
 '3-Shirts',
 'M',
 'summer-sand.jpg'),

('Urban Street Graphic Tee',
 'Bold front graphic with durable screen printing and a modern slim silhouette.',
 30.00,
 'White',
 'Graphic',
 '3-Shirts',
 'L',
 'urban-street-white.jpg'),

('Olive Everyday Tee',
 'Versatile olive tone with soft-touch fabric and reinforced collar to prevent stretching.',
 23.00,
 'Olive',
 'Solid',
 '3-Shirts',
 'M',
 'olive-everyday.jpg'),

('Washed Denim Blue Tee',
 'Garment-dyed for a slightly faded finish and lived-in comfort from the first wear.',
 27.00,
 'Denim Blue',
 'Solid',
 '3-Shirts',
 'L',
 'washed-denim-blue.jpg'),

('Minimal Script Logo Tee',
 'Subtle embroidered chest logo with a clean and modern aesthetic.',
 29.00,
 'Cream',
 'Logo',
 '3-Shirts',
 'M',
 'minimal-script-cream.jpg'),

('Performance Stretch Tee',
 'Cotton-spandex blend offering flexibility and moisture control for active days.',
 34.00,
 'Black',
 'Solid',
 '3-Shirts',
 'L',
 'performance-stretch-black.jpg'),

('Autumn Rust Tee',
 'Warm rust color in a soft midweight cotton, ideal for fall layering.',
 24.00,
 'Rust',
 'Solid',
 '3-Shirts',
 'M',
 'autumn-rust.jpg'),

('Coastal Blue Graphic Tee',
 'Ocean-inspired artwork printed with eco-friendly inks on breathable cotton fabric.',
 28.00,
 'Coastal Blue',
 'Graphic',
 '3-Shirts',
 'L',
 'coastal-blue-graphic.jpg'),

('Limited Edition Drop Tee',
 'Seasonal release featuring exclusive artwork and premium cotton construction.',
 36.00,
 'Black',
 'Graphic',
 '3-Shirts',
 'M',
 'limited-edition-drop.jpg'),

('Slim Fit White Tee',
 'Tailored slim-fit silhouette crafted from soft ring-spun cotton for a clean look.',
 22.00,
 'White',
 'Solid',
 '3-Shirts',
 'S',
 'slim-fit-white.jpg'),

('Relaxed Fit Oversized Tee',
 'Modern oversized cut with dropped shoulders and heavyweight cotton fabric.',
 33.00,
 'Stone',
 'Solid',
 '3-Shirts',
 'XL',
 'relaxed-oversized-stone.jpg'),

('Classic V-Neck Tee',
 'Clean V-neck design made from breathable cotton with a comfortable everyday fit.',
 21.00,
 'Black',
 'Solid',
 '3-Shirts',
 'M',
 'classic-vneck-black.jpg');